import sys

fail = True

if fail:
    print("TRIAL FAIL")
    sys.exit(1)
